# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test Coverage
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4

      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      # Step 3: Install dependencies and generate coverage
      - name: Install Dependencies and Run Coverage
        run: |
          npm ci
          npm run coverage # Ensure this generates `coverage/lcov.info`

      # Step 4: Debug to ensure coverage file exists
      - name: List Coverage Files
        run: |
          ls -l coverage
          cat coverage/lcov.info

      # Step 5: Upload coverage to Coveralls
      - name: Upload to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage/lcov.info